### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by Zengpr** [CSAILVision/gandissect#8]
I have the problem:
RuntimeError: CUDA error: out of memory

although I have change the batch_size to 1

**Comment by davidbau** [comment]
Do you know what stage of the computation is running out of memory?  I.e., is it at the beginning, when it is collecting quantile data?

If you specify fewer layers to dissect, it will take less memory.  Also, if you take care to dissect layers which have smaller representations (e.g., lower resolution), it will take less memory - and often these smaller representation layers are the interesting ones also.

**Comment by davidbau** [comment]
Feel free to contact me with more details if the tips above don't work for you.
