### ISSUE TITLE
Support for pytorch 1.0.1

### ISSUE THREAD

**Issue by Richardwan7** [CSAILVision/gandissect#9]
Will there be plan to have the script support pytorch 1.0.1? I got the following error when executing ./travis.sh with pytorch 1.0.1: "ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead"

**Comment by davidbau** [comment]
Yup, we'll move to support pytorch 1.0.1.  The semantic image segmentation that we use currently depends on pytorch 0.4 but they plan to move to pytorch 1, so when that is ready, we'll upgrade also.

**Comment by davidbau** [comment]
This should be fixed now.
